const sampleComicdetail =[
    {
      "bookName": "To Kill a Mockingbird",
      "authorName": "Harper Lee",
      "yearOfPublication": 1960,
      "price": 15.99,
      "discount": 10,
      "numberOfPages": 281,
      "condition": "new",
      "description": "A powerful exploration of race and injustice in the American South.",
      "publisher": "J.B. Lippincott & Co.",
      "language": "English",
      "stock": 25
    },
    {
      "bookName": "1984",
      "authorName": "George Orwell",
      "yearOfPublication": 1949,
      "price": 12.50,
      "numberOfPages": 328,
      "condition": "used",
      "stock": 5
    },
    {
      "bookName": "The Great Gatsby",
      "authorName": "F. Scott Fitzgerald",
      "yearOfPublication": 1925,
      "price": 10.99,
      "discount": 5,
      "numberOfPages": 180,
      "condition": "new",
      "publisher": "Scribner",
      "language": "English",
      "stock": 18
    },
    {
      "bookName": "Pride and Prejudice",
      "authorName": "Jane Austen",
      "yearOfPublication": 1813,
      "price": 8.99,
      "numberOfPages": 279,
      "condition": "used",
      "description": "A classic novel of manners and moral growth.",
      "language": "English",
      "stock": 12
    },
    {
      "bookName": "The Catcher in the Rye",
      "authorName": "J.D. Salinger",
      "yearOfPublication": 1951,
      "price": 9.99,
      "numberOfPages": 214,
      "condition": "new",
      "publisher": "Little, Brown and Company",
      "language": "English",
      "stock": 30
    },
    {
      "bookName": "Moby-Dick",
      "authorName": "Herman Melville",
      "yearOfPublication": 1851,
      "price": 14.99,
      "discount": 15,
      "numberOfPages": 585,
      "condition": "new",
      "description": "An epic tale of obsession and revenge.",
      "publisher": "Harper & Brothers",
      "language": "English",
      "stock": 10
    },
    {
      "bookName": "The Hobbit",
      "authorName": "J.R.R. Tolkien",
      "yearOfPublication": 1937,
      "price": 20.00,
      "numberOfPages": 310,
      "condition": "used",
      "description": "A prelude to the Lord of the Rings, filled with adventure.",
      "publisher": "George Allen & Unwin",
      "language": "English",
      "stock": 7
    },
    {
      "bookName": "War and Peace",
      "authorName": "Leo Tolstoy",
      "yearOfPublication": 1869,
      "price": 25.00,
      "numberOfPages": 1225,
      "condition": "new",
      "description": "A complex and philosophical novel about Russian society.",
      "publisher": "The Russian Messenger",
      "language": "Russian",
      "stock": 6
    },
    {
      "bookName": "The Odyssey",
      "authorName": "Homer",
      "yearOfPublication": -800,
      "price": 18.99,
      "numberOfPages": 541,
      "condition": "new",
      "language": "Greek",
      "stock": 14
    },
    {
      "bookName": "Crime and Punishment",
      "authorName": "Fyodor Dostoevsky",
      "yearOfPublication": 1866,
      "price": 11.99,
      "discount": 8,
      "numberOfPages": 671,
      "condition": "used",
      "publisher": "The Russian Messenger",
      "language": "Russian",
      "stock": 8
    },
    {
      "bookName": "Brave New World",
      "authorName": "Aldous Huxley",
      "yearOfPublication": 1932,
      "price": 13.50,
      "numberOfPages": 268,
      "condition": "new",
      "description": "A dystopian novel exploring futuristic themes.",
      "publisher": "Chatto & Windus",
      "language": "English",
      "stock": 20
    },
    {
      "bookName": "The Brothers Karamazov",
      "authorName": "Fyodor Dostoevsky",
      "yearOfPublication": 1880,
      "price": 16.99,
      "numberOfPages": 796,
      "condition": "used",
      "description": "A deep philosophical discussion of free will and morality.",
      "publisher": "The Russian Messenger",
      "language": "Russian",
      "stock": 4
    },
    {
      "bookName": "The Divine Comedy",
      "authorName": "Dante Alighieri",
      "yearOfPublication": 1320,
      "price": 22.00,
      "discount": 12,
      "numberOfPages": 798,
      "condition": "new",
      "publisher": "John Murray",
      "language": "Italian",
      "stock": 9
    },
    {
      "bookName": "The Alchemist",
      "authorName": "Paulo Coelho",
      "yearOfPublication": 1988,
      "price": 17.99,
      "numberOfPages": 208,
      "condition": "new",
      "description": "A philosophical book about following your dreams.",
      "publisher": "HarperTorch",
      "language": "Portuguese",
      "stock": 22
    },
    {
      "bookName": "The Picture of Dorian Gray",
      "authorName": "Oscar Wilde",
      "yearOfPublication": 1890,
      "price": 10.99,
      "numberOfPages": 254,
      "condition": "used",
      "publisher": "Ward, Lock & Co.",
      "language": "English",
      "stock": 13
    },
    {
      "bookName": "Don Quixote",
      "authorName": "Miguel de Cervantes",
      "yearOfPublication": 1605,
      "price": 19.50,
      "numberOfPages": 863,
      "condition": "new",
      "publisher": "Francisco de Robles",
      "language": "Spanish",
      "stock": 11
    },
    {
      "bookName": "The Road",
      "authorName": "Cormac McCarthy",
      "yearOfPublication": 2006,
      "price": 15.99,
      "discount": 5,
      "numberOfPages": 287,
      "condition": "new",
      "description": "A father and son journey through a post-apocalyptic landscape.",
      "publisher": "Alfred A. Knopf",
      "language": "English",
      "stock": 17
    },
    {
      "bookName": "The Shining",
      "authorName": "Stephen King",
      "yearOfPublication": 1977,
      "price": 14.99,
      "numberOfPages": 447,
      "condition": "used",
      "description": "A chilling horror story set in an isolated hotel.",
      "publisher": "Doubleday",
      "language": "English",
      "stock": 6
    },
    {
      "bookName": "The Grapes of Wrath",
      "authorName": "John Steinbeck",
      "yearOfPublication": 1939,
      "price": 13.00,
      "numberOfPages": 464,
      "condition": "new",
      "description": "A portrayal of Dust Bowl migrant families' hardships during the Great Depression.",
      "publisher": "The Viking Press",
      "language": "English",
      "stock": 14
    },
    {
      "bookName": "One Hundred Years of Solitude",
      "authorName": "Gabriel García Márquez",
      "yearOfPublication": 1967,
      "price": 18.99,
      "numberOfPages": 417,
      "condition": "new",
      "description": "A multi-generational tale of the Buendía family in the town of Macondo.",
      "publisher": "Harper & Row",
      "language": "Spanish",
      "stock": 10
    }
  ];

  module.exports = { data: sampleComicdetail };
  